# Generated by Django 5.1.1 on 2024-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="name",
            field=models.CharField(default="My Playlist", max_length=128),
        ),
    ]
