# Generated by Django 5.1.3 on 2024-12-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0003_alter_album_album_id_alter_artist_artist_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist_song",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AlterField(
            model_name="playlist_song",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_songs",
                to="musicapp.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlist_song",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="song_playlists",
                to="musicapp.song",
            ),
        ),
    ]
