# Generated by Django 5.1.2 on 2024-12-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0004_rename_user_playlist_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="spotify_id",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
